# Generated by Django 5.0.7 on 2024-07-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_refreshtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
